### ISSUE TITLE
[Usability] Join Testflight button is hidden on mobile

### ISSUE THREAD

**Issue by JanGross** [kepelet/client.flooo.club#1]
The "Join Testflight" button is only visible with a minimum width of 60em, making it hidden on mobile devices.
Joining the Testflight program from an iPhone is therefore unnecessarily cumbersome (e.g. zooming out in landscape mode) 
especially if a larger device is not available.

**For reference**  
The `.c-button--cta-navbar` class is hidden by default
https://github.com/kepelet/client.flooo.club/blob/291a20ccaae692c4a63d076dbef19e588c46fe5f/assets/css/style.css#L202-L203
And overridden in the media query at 
https://github.com/kepelet/client.flooo.club/blob/291a20ccaae692c4a63d076dbef19e588c46fe5f/assets/css/style.css#L488-L491

**Screenshot on an iPhone 15**
<img src="https://github.com/user-attachments/assets/b5e0f341-8143-41ad-997e-dcc93a447801"  width="150">

**Comment by faultables** [comment]
this is intentional as we currently can't install both versions (App Store & TestFlight) due to the same bundle identifiers and the "gap" in the release cycle between the versions is relatively short aaaaand foremost i personally encourage anyone that knows flo from the website to install the App Store one — but, the room of improvement is always welcome! what do you think?

**Comment by JanGross** [comment]
>  i personally encourage anyone that knows flo from the website to install the App Store one 

This is a fair argument. Not advertising the Test Flight as the first thing on the homepage seems reasonable for regular users.
My suggestion would be an additional FAQ item along the lines of:

> **Is there a TestFlight program?**
> A frequently updated development build is available. [Join here.](https://testflight.apple.com/join/913htqtU)

That way a user would only find the TestFlight link by looking for it and scrolling pretty much all the way down :)

**Comment by faultables** [comment]
thanks for the suggestion! it's live now (https://github.com/kepelet/client.flooo.club/commit/2622368948e476cd9f5ce65e9aba043e60f2c8dd)

![image](https://github.com/user-attachments/assets/2d4b5671-da18-4a5c-a2fd-e86b597f0616)

**Comment by JanGross** [comment]
Awesome 👍🏼
